# Getting Started with TensorFlow 2.0 in 7 Days
## 1.3 Getting Started

In [1]:
# install tensorflow
!pip install tensorflow==2.0.0-beta0

Let's start by importing the libraries we need

In [1]:
#import tensorflow
import tensorflow as tf

#import numpy
import numpy as np

### Functions
we will declare a function to carry out the computation we need. This function is decorated by an annotation.

We randomly generate our weights and bias from random normal distributions.

We then proceed to multiply and add, just as in the equation. One thing to note is the flag `transpose_b`, which lets the equation transpose our vector into the right shape.

In [2]:
@tf.function
def predict(x):
  # declare our weights to have the same number of columns as our input
  w = np.random.randn(1, x.shape[1])
  # declare our bias to have the same number of rows but only one column
  b = np.random.randn(x.shape[0], 1)
  #carry out the operation
  return tf.matmul(x, w, transpose_b=True) + b

Let's generate a random set of data, which has 10 rows and 3 columns

In [3]:
x = np.random.rand(10, 3)
print(x)

[[0.24814373 0.24248074 0.26670315]
 [0.8780466  0.38537597 0.38230948]
 [0.05728538 0.11955149 0.56024601]
 [0.74581702 0.9110419  0.4001707 ]
 [0.28548562 0.17305893 0.37254218]
 [0.95662496 0.26862723 0.18733195]
 [0.60230792 0.13485019 0.95569995]
 [0.11277017 0.91417087 0.63693215]
 [0.84113142 0.62645807 0.36577241]
 [0.74910054 0.05211972 0.04999793]]


Let's proceed to make a prediction. Our output should have only one value for each row.

In [4]:
y_hat = predict(x)
print(y_hat)

tf.Tensor(
[[-0.12315617]
 [ 1.01311381]
 [-1.90326031]
 [ 0.58358723]
 [ 0.61882852]
 [ 0.44035145]
 [ 0.92616878]
 [-1.7121107 ]
 [-0.13416682]
 [ 0.018271  ]], shape=(10, 1), dtype=float64)
